### ISSUE TITLE
Geofencing Android SDK - Define tracking parameters from a Json or an URL

### ISSUE THREAD

**Issue by lpernelle-wgs** [woosmap/woosmap-geofencing-android-sdk#48]
# Problem
## What

Simplify Woosmap Geofencing SDK tracking configuration.
Externalize WoosmapGeofencing SDK tracking configuration, upload Json data in the SDK and refresh these data periodically.
## Why

In the current version, to initialize and start location collection, client app has to use a standard tracking profile (liveTracking, passiveTracking or visitTracking) or manually set each parameter in the SDK. The first method is too restrictive and the second one is too complexe. 

## Who

Clients | Customer Care | Sales | Marketing

# Solution
## How

- [ ] Edit the startTracking method to allow client app to provide Json data or URL linked to a Json file
- [ ] Add an automatic process to refresh the Json file upload periodically 
- [ ] Add a tracking parameter to define the gap between two Json file refresh

### Expected Change Level

Major
### Dependencies

N/A

# Definition of Done (DoD)

- [ ] task one
- [ ] task two

# Acceptance Criteria (AC)

- [ ] behaviour one
- [ ] behaviour two

# Documentation

Internal: JavaDoc Reference
External: developers.woosmap.com
